---
title: "Agenda 2024"
---

{{< include _navbar.qmd >}}

8:30 – **Welcome coffee and tea**

9:30 – **Opening talk**  
Mark Bailey – Locum Respiratory Consultant and Clinician-who-codes

\

## 9:35 – Morning session 1

*9:35 – Chair – TBC*

9:40 – **The patient's perspective**  
Stephen Rowley - Patient advocate and STEM career – Patient representative

9:50 – **Shared care record in BOB**  
Nadia Kuftinoff - Senior Digital Delivery Lead, Buckinghamshire, Oxfordshire & West Berkshire ICB

10:00 – **Migr.AI.ne: Using convolutional neural networks and LLMs to process patient diaries**  
Alexandre Mathy - Consultant Neurologist at the Great Western Hospital, Oxford University Hospitals and Lead Clinician for the Community Headache Clinic.

10:10 – Q&A

\

## 10:25 – Coffee break

\

## 11:05 – Morning session 2

*11:05 – Chair – TBC*

*11:10 – TBC*

*11:25 – TBC*

11:35 – **Clinical Digital Manifesto**  
Marcus Baw - Locum GP and ED doctor and clinician-who-codes &  
Tom Stocker - Digital and innovation leader, The Clatterbridge Cancer Centre NHS Foundation Trust; Director, Care Cascades

11:45 – Q&A

\

## 12:00 – Debate

**“This house believes that the NHS should be using open source where ever possible”**

*Chair – TBC*

**For** – Paul Drake - Plastic surgeon, CCIO and clinician-who-codes at East Grinstead Hospital

**Against** – Geoff Revill 

(2 x 10 min presentations, 2 x 5 min responses, 20 min Q&A to the floor)

\

## 12:50 – 13:50 – Lunch with posters

\


## 13:50 – Afternoon session 1

*13:50 – Chair – TBC*

13:55 – **Games, cheatsheets and the NHS**  
Simon Latimer - Dermatology Systems Manager, University Hospital Southampton NHS Foundation Trust

14:05 – **Digital Innovation at Oxford University Hospital**  
Grant Vallance - Information Manager, Oxford University Hospitals NHS Trust

*14:15 – TBC*

14:25 – Q&A

\

## 14:40 – Coffee break

\

## 15:20 – Afternoon session 2

*15:20 – Chair – TBC*

15:25 – Poster awards

15:35 – **MedEd Connect: Transforming Medical Education through Digital Technology**  
Sobath Premaratne - Vascular and Endovascular Surgeon and part-time renal transplant surgeon in London. Ex requirements analyst and software developer

15:55 – **Digital Growth Charts**
Simon Chapman - Paediatric Consultant and clinician-who-codes

16:05 – Q&A

16:20 – close