---
title: "Sponsorship of Let’s Talk Digital Conference, October 24th, 2024"
---

The **Let’s Talk Digital Conference** is the main event in the calendar for those passionate about and working towards **better digital healthcare in the NHS**. We enable open debate about difficulties and real wins from those implementing digital change at the front line. This is a **great chance** for your company to engage with forward thinking professionals in the digital health arena. Let's Talk Digital Conference 2024 is being held on Thursday the 24th of October at Cheltenham General Hospital. This is a **hybrid event**, with both online and face-to-face attendees. Previous years we have had **over 140 attendees**, both in the UK and as far away as Sweden and Brazil. This year’s theme is open (eg source, data, learning and standards). The conference focuses each year on **great digital innovation and implementation at the frontline**. Further information about the conference can be found at [here](https://letsdodigital.org/conferences/2024/). There are two great packages to chose from.

\

## Package 1 - £500
1. Access to near 100 virtual delegates. If you provide us with a 5-10 min video, we can play this online for viewers between sessions (eg coffee breaks and lunch breaks).
2. Shout out to your company on the Let's Do Digital (www.letsdodigital.org) website homepage for a year.
3. Shout out to your company at the conference at the beginning of the day, between sessions and at the end of the day.
4. Your video will be hosted on the Let's Do Digital YouTube channel (https://www.youtube.com/channel/UCO1NX3whqamwNJOZ72p9WTA).
5. Shout out to your company when Let's Do Digital sends conference related emails to its 500+ mailing list.

\

## Package 2 - £1000
1. All of the above, plus...
2. A stall at the conference.
3. Access to engage with near 100 delegates in person on the day.

\

Please contact us at [mark@letsdodigital.org](mailto:mark@letsdodigital.org) if you wish to discuss sponsorship further.

Mark, Lead for Let’s Do Digital