project:
  type: website
  resources:
    - "documents/*"

website:
  title: "Let's Do Digital"
  site-url: "https://letsdodigital.org/"
  navbar:
    left:
      - href: learn/index.qmd
        text: Learn
      - href: conferences/2024/index.qmd
        text: Conference
      - href: tickets/index.qmd
        text: "Tickets"
      - posts.qmd
      - forum.qmd
      - services-we-offer.qmd
      - who-are-we.qmd
      
  page-footer: 
    left: 
      - href: contact.qmd
        text: Contact
      - href: privacy-policy.qmd
        text: Privacy Policy
      - href: company-information.qmd
        text: Company information
      - href: sponsor.qmd
        text: Sponsor us
      - href: paying-the-team.qmd
        text: Paying the team
      - href: eohi/business-case.qmd
        text: Essentials of Health Informatics
    right: 
      - icon: github
        href: https://github.com/letsdodigital
      - icon: twitter 
        href: https://twitter.com/letsdodigitalci
  twitter-card: true
      

  favicon: media/ldd-logo.png

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



