project:
  type: website

website:
  title: "Let's Do Digital"
  site-url: "https://letsdodigital.org/"
  navbar:
    left:
      - href: learn/index.qmd
        text: Learn
      - text: Conferences
        menu:
          - href: conferences/2024/index.qmd
            text: "2024"
          - href: conferences/2023/index.qmd
            text: "2023"
          - href: conferences/2022/index.qmd
            text: "2022"
      - href: webinars/index.qmd
        text: "Webinars"
      - href: tickets/index.qmd
        text: "Tickets"
      - href: sponsor.qmd
        text: Sponsor
      - posts.qmd
      - who-are-we.qmd
      - contact.qmd
  page-footer: 
    left: 
      - href: contact.qmd
        text: Contact
      - href: privacy-policy.qmd
        text: Privacy Policy
    right: 
      - icon: github
        href: https://github.com/letsdodigital
      - icon: twitter 
        href: https://twitter.com/letsdodigitalci
      

  favicon: media/ldd-logo.png

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



