---
title: "Paying the team"
---

**Let's Do Digital** is dedicated to creating educational content in the field of digital healthcare and also designing and building better digital health systems. We believe that profits made through Let's Do Digital should be fairly shared with those involved in helping run Let's Do Digital. Hence, Let's Do Digital sets out the below criteria for paying those involved in its ongoings.

### Overview

- A 15% payback into Let's Do Digital for covering costs and for helping with future endeavours.
- The remaining monies will then be divided as a proportion of hours worked by individuals.
- Profits received relating directly with an event will be shared with team members involved in said event.
- If there are no profits, the losses will be covered by Let's Do Digital.

### Live Teaching Sessions

- This includes webinars and courses.
- A chair of a session can claim up to 1 hour preparation time for every 1 hour of the session.
- For new material, the speaker can claim up to 3 hours of preparation time for every 1 hour of the session.
- For previously covered materials, the speaker can claim up to 1 hour of preparation time for every 1 hour of the session.
- For tutors, they can claim up to 1 hour of preparation time for every 1 hour of teaching.
- Admin support time is very variable, but will be limited to a maximum of 5 hours for every 1 hour of the session.
- Profits made after and directly in relation to the teaching event will be shared out as outlined above on a yearly basis. These post-events profits will be shared until 5 years after the event.

### Self-Paced Teaching Modules

- 40% of profits will be paid to those who create these self-paced modules. If more than one person has been involved in the creation of said materials, the 40% payout will be divided as a proportion of time spent creating this material.

### Conferences

- This is in regards to the Let's Talk Digital Conference run by the Let's Do Digital team.
- We are hoping to pay for speakers and chairs for future conferences. Any net profits from the conference this year will be shared with the committee helping to run the conference.

### Software house

To be later confirmed.

### Subject to change

As the sponsorship method outline above is not a fully tried and tested one, it may be subject to change. We will provide any updates regarding any changes on this page.
