---
title: "Services we offer"
---

At Let's Do Digital, we offer a wide range of services. Whether you are looking for education, training, expert input or even building your own healthcare digital system, we are here to help you out.

## Education

**Mentoring:** You will have one-on-one sessions with your own mentor, selected to best help you in the career path you are wishing to pursue. See our [mentoring](mentoring.qmd) page for further details.

**Tutoring:** We can provide a tutor for a range of topics. Currently, the most sort after topic is help with programming, but do contact us with any digital health related subject if you are interested. See our [tutoring](tutoring.qmd) page for further details.

**Organised local teaching:** Do you need digital health teachings at your local medical school, nursing school, GP practice, hospital, ICB, company? If so, do get in contact and we would be happy to create bespoke teaching materials and courses for your needs.

**Essentials of Health Informatics:** We are in the process of building this essential guide in Digital Health. This will be an open source and online resource, to help the novice and even the advanced practitioner master Digital Health. Further details will be available shortly.


## Learnings

At Let's Do Digital, we are actively engaging with frontline clinicians to help build digital solutions that just make healthcare better. We are currently building out our new resource highlighting great digital innovation at the frontline. Look out for **Unlocked - Spotlight on Frontline Digital Health**.


## Stakeholder engagement

Do you need help engaging with key stakeholders in your next digital health implementation? Our team have several members with experience in taking forward your new digital health idea and getting the end-user input to create a product fit for purpose. Email us for further details.


## Prototyping

We provide a professional service to help you realise your dream healthcare app. We can help you navigate the need of the clinician in your app, get user-experience right and build a working prototype of your new digital health technology.


## Contact us

Ready to take the next step in your digital healthcare journey? Email us at [info@letsdodigital.org](mailto:info@letsdodigital.org).