---
title: "Module-5"
author: "David Tang"
format: revealjs
logo: /media/ldd-logo.png
css: /slides.css
title-slide-attributes:
  data-background-color: "#0D4848"
---

## Variables in JavaScript

- Variables are like containers that hold information (data) in your code.
- This data can be numbers, text, or even more complex data structures.
- JavaScript allows you to:
  - Declare variables: Create a named container to store data.
  - Assign values: Put data into the container.
  - Manipulate values: Change the data stored in the container (e.g., perform calculations).

---

## Example variables

```javascript
let name = "John";
let age = 25;
let isPatient = true;
let conditions = ["diabetes", "cataracts", "hyperlipidaemia"];
```

---

## The role of Javascript in frontend healthcare applications.

- Many modern clinical applications rely heavily on JavaScript for their functionality.
- Examples:
  - Electronic Health Records (EHRs): Dynamic forms, patient data validation, interactive dashboards.
  - Telehealth Platforms: Real-time video conferencing, chat features, remote patient monitoring.
  - Medical Imaging Software: Interactive image viewing, annotation tools, 3D visualizations.
  - Decision Support Tools: Calculate risk scores, provide treatment recommendations, display interactive charts.
- Modern JavaScript frameworks like React, Angular, and Vue.js are used to build complex and scalable web applications.

---

## What's in This Module

- Introduction to **JavaScript**: Bringing interactivity to websites.
- Why use JavaScript? The importance of dynamic content and behavior.
- **Variables** in JavaScript: Storing and manipulation of data.
- Setting up a **JavaScript testing sandbox**.

- Followup module 6:
  - **Loops** in JavaScript: Automating repetitive tasks.
  - Building our first function: A phone number validator.

## Tutor groups

- Tutor groups:
  - ?

## Next Session

- More on Javascript
