name: Main Tasks

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.1.0'

      - name: Install dependencies
        run: npm install

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: run CI CD tasks
        run: bash cicd.sh

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: If failure, revert commit
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              // Set Git user config
              execSync('git config --global user.email "info@letsdodigital.org"', { stdio: 'inherit' });
              execSync('git config --global user.name "Lets Do Digital"', { stdio: 'inherit' });
              
              // Get commit details
              const commitSha = process.env.GITHUB_SHA;
              const commitInfo = execSync(`git cat-file -p ${commitSha}`, { cwd: process.env.GITHUB_WORKSPACE }).toString();
              const isMergeCommit = commitInfo.includes('parent') && commitInfo.split('\n').filter(line => line.startsWith('parent')).length > 1;
              
              // Revert command
              const revertCommand = isMergeCommit ? `git revert --no-commit -m 1 ${commitSha}` : `git revert --no-commit ${commitSha}`;
              execSync(revertCommand, { cwd: process.env.GITHUB_WORKSPACE, stdio: 'inherit' });
              
              // Commit and push
              execSync(`git commit -m "Revert commit ${commitSha} due to test failure"`, { cwd: process.env.GITHUB_WORKSPACE, stdio: 'inherit' });
              execSync(`git push origin main`, { cwd: process.env.GITHUB_WORKSPACE, stdio: 'inherit' });
            } catch (error) {
              console.error(`Revert failed: ${error.message}`);
              process.exit(1);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-deploy:
    needs: testing
    runs-on: ubuntu-latest
    name: Build and Deploy
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
