name: Non-Main Tasks

on:
  push:
    branches-ignore:
      - master 
      - main
      - "pull-request-for-*"

permissions:
  contents: write

jobs:
  # testing:
  #   runs-on: ubuntu-latest
  #   name: Testing
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '23.1.0'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Set up Quarto
  #       uses: quarto-dev/quarto-actions/setup@v2

  #     - name: run CI CD tasks
  #       run: bash cicd.sh

  create_pr:
    # needs: testing
    name: Create / Update PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: create pull request
        run: gh pr create -B main -H develop --title 'Merge develop into main' --body 'Created by GitHub action'
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}

      