name: Non-Main Tasks

on:
  push:
    branches-ignore:
      - master 
      - main
      - "pull-request-for-*"

permissions:
  contents: write

jobs:
  cicd_pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.1.0'

      - name: Install dependencies
        run: npm install

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: run CI CD tasks
        run: bash cicd.sh
      
      # - name: Configure Git
      #   run: |
      #     git config --global user.email "quarto-github-actions-publish@example.com"
      #     git config --global user.name "Quarto GHA Workflow Runner"

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     token: ${{ secrets.PAT }}
      #     commit-message: "Automated changes from CI/CD pipeline"
      #     branch: "pull-request-for-${{ github.ref_name }}"
      #     title: "Automated changes from CI/CD pipeline"
      #     body: "This PR contains automated changes from the CI/CD pipeline."
      #     base: main

  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request using GitHub Script
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = process.env.GITHUB_REF.replace('refs/heads/', '');
            const baseBranch = "main";  // Change this to your target branch if needed
            const title = `PR: Review changes from ${branchName}`;
            const body = "This pull request was created automatically to review the changes from the recent commit.";

            // Create the pull request using the REST API via github.rest
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branchName,
              base: baseBranch,
              title: title,
              body: body,
            });
            console.log("Pull Request URL:", pullRequest.html_url);

      